### ISSUE TITLE
Defered render not show anything

### ISSUE THREAD

**Issue by happydpc** [MeirBon/rfw-rs#3]
As the screenshot shows, it doesn't show anything. The shader and model directory is correct.

![image](https://user-images.githubusercontent.com/771776/86256058-6f2a3580-bbea-11ea-8562-d5ba560e4724.png)

**Comment by MeirBon** [comment]
I think I've had this before on some PCs. It only occurs on Windows it seems, I think it's a bug in wgpu but I'm not sure what the cause is.

Could you check [this branch](https://github.com/MeirBon/rfw-rs/tree/fix-black-screen-wgpu)? IIRC I fixed it before by explicitly using DX12 instead of Vulkan as the wgpu backend on Windows.

**Comment by happydpc** [comment]
Seems still not work on windows.

**Comment by MeirBon** [comment]
I made a mistakes, should be fixed now
